CREATE DATABASE DEMO_SR1_{{ENV}};
CREATE SCHEMA DEMO_SR1;
CREATE TABLE SUPPLIER
(
   FIRST_NAME VARCHAR
  ,LAST_NAME VARCHAR
);

CREATE TABLE CUSTOMERS
(
   CUSTOMER_ID VARCHAR
  ,CUSTOMER_NAME VARCHAR
);