CREATE OR REPLACE DATABASE IF NOT EXISTS DEMO_SRDB_{{ENV}};
CREATE OR REPLACE SCHEMA IF NOT EXISTS DEMO_SRDB_{{ENV}}.DEMO_SR;

CREATE  OR REPLACE TABLE DEMO_SRDB_{{ENV}}.DEMO_SR.HELLO_WORLD
(
   FIRST_NAME VARCHAR(100),
   LAST_NAME  VARCHAR(100)
);

CREATE OR REPLACE TABLE DEMO_SRDB_{{ENV}}.DEMO_SR.CUSTOMERS
(
   CUSTOMER_ID   VARCHAR(50),
   CUSTOMER_NAME VARCHAR(200)
);
