CREATE DATABASE IF NOT EXISTS DEMO_SRDB_{{ENV}};
CREATE SCHEMA IF NOT EXISTS DEMO_SRDB_{{ENV}}.DEMO_SR;

CREATE TABLE DEMO_SRDB_{{ENV}}.DEMO_SR.HELLO_WORLD
(
   FIRST_NAME VARCHAR(100),
   LAST_NAME  VARCHAR(100)
);

CREATE TABLE DEMO_SRDB_{{ENV}}.DEMO_SR.CUSTOMERS
(
   CUSTOMER_ID   VARCHAR(50),
   CUSTOMER_NAME VARCHAR(200)
);
