CREATE OR REPLACE DATABASE Account_{{ENV}};
CREATE OR REPLACE SCHEMA Account_{{ENV}}.Action_SR;

CREATE OR REPLACE TABLE CUSTOMERS
(
   CUSTOMER_ID VARCHAR,
   CUSTOMER_NAME VARCHAR
);

CREATE OR REPLACE TABLE SUPPLIER
(
   SUPPLIER_ID VARCHAR,
   SUPPLIER_NAME VARCHAR
);